### ISSUE TITLE
Script should ask to restart mailboxd

### ISSUE THREAD

**Issue by wolfyzvf** [jorgedlcruz/Zimbra#3]
The script should ask to restart the mailboxd process.
Here is the diff to apply : 
diff -u ../zimbra-chrome45-fix.sh.orig zimbra-chrome45-fix.sh
--- ../zimbra-chrome45-fix.sh.orig	2015-09-03 12:33:01.000000000 +0200
+++ zimbra-chrome45-fix.sh	2015-09-03 12:37:01.000000000 +0200
@@ -12,8 +12,7 @@

 ## Downloading the fixed Files from GitHub
 echo "Downloading the fixed Files from GitHub"
-wget https://raw.githubusercontent.com/jorgedlcruz/Zimbra/master/Zimbra%20Google%20Chrome%2045%20Fix/_base2skin.css
-wget https://raw.githubusercontent.com/jorgedlcruz/Zimbra/master/Zimbra%20Google%20Chrome%2045%20Fix/_base3skin.css
\+wget https://raw.githubusercontent.com/jorgedlcruz/Zimbra/master/Zimbra%20Google%20Chrome%2045%20Fix/_base2skin.cs https://raw.githubusercontent.com/jorgedlcruz/Zimbra/master/Zimbra%20Google%20Chrome%2045%20Fix/_base3skin.css

 ## Move the downloaded Files into the proper folder
 echo "Move the downloaded Files into the proper folder"
@@ -26,7 +25,15 @@
 chown zimbra:zimbra /opt/zimbra/jetty/webapps/zimbra/skins/_base/base3/skin.css

 ## Restart the Mailbox Service
-echo "Restart the Mailbox Service"
-su - zimbra -c 'zmmailboxdctl restart'
\+read -p "To finish the installation you need to restart the mailboxd process. This will cause a service disruption.
\+Are you sure you want to continue? " -n 1 -r
\+echo    # (optional) move to a new line
\+if [[ ! $REPLY =~ ^[Yy]$ ]]
\+then
\+    exit 1
\+else
\+   echo "Restart the Mailbox Service"
\+   su - zimbra -c 'zmmailboxdctl restart'
\+fi

 echo "Now, all the users must do logout and login, and everything should work"

**Comment by jorgedlcruz** [comment]
Done, thank you.
